### ISSUE TITLE
Replace Poetry with Conda?

### ISSUE THREAD

**Issue by l0b0** [linz/emergency-management-tools#170]
Since we basically have to use Conda now in order to install GDAL on Windows, we might want to reduce the complexity of installing the requirements by removing the need for Poetry.

Requirements:

- A lock file with hashes for each package, equivalent to `poetry.lock`. This ensures that any re-release of a version (malicious or accidental) is treated as an error, and that builds are more reproducible.
- `poetry.lock` and `pyproject.toml` should be replaced with an `environment.yml`.
- Documentation files have to be updated.
- Activating the Nix shell should be sufficient to install all the prerequisites, as it is now with poetry2nix. See for example the [Nix wiki](https://nixos.wiki/wiki/Python) for some ideas.

Wanted features:

- The CI jobs should be simplified.
- Avoid Poetry Windows issues ([1](https://github.com/python-poetry/poetry/issues/1031), [2](https://github.com/python-poetry/poetry/issues/7589))

Issues:

- [Dependabot does not support Conda](https://github.com/dependabot/dependabot-core/issues/2227), and has [stagnated since 2020](https://github.com/dependabot/dependabot-core/blob/main/CONTRIBUTING.md#contributing-new-ecosystems), so it's unlikely to be added anytime soon. [Work is underway to support Conda in Renovate](https://github.com/renovatebot/renovate/issues/2213).
- Conda doesn't have any lock file functionality built in. There's [conda-lock](https://anaconda.org/conda-forge/conda-lock), but since that's a separately installed package there would still be the problem of locking conda-lock itself. :cry:
- There's no conda2nix or similar for Nix support.

Conclusion: This would be even more of a pain to maintain than the current solution. Scrapping for now.

**Comment by ameya-deshmukh** [comment]
Hi @l0b0 I see you've mentioned a lack of something like conda2nix for this issue. Do you think a tool like conda2nix would be useful for you? If so, will begin work on it :)

**Comment by l0b0** [comment]
Hi @ameya-deshmukh, I think it's an excellent idea to build it! I think it would be very useful for the community.

That said, I probably wouldn't be able to help develop or test it until it's stable enough for production use (assuming 1+ years of multiple people developing, and at least a handful of people using it regularly). This is a work repository, it's currently the only one I'm working on which uses Conda, and while the current solution is clunky and might fail in the future if Conda and Poetry don't play nice, the current code does work.

**Comment by ameya-deshmukh** [comment]
Hi, thanks so much for the input! 

Yeah for sure, long way for it to get to production, just wanted to get some inputs on whether something like that would be useful, and I think I've got my answer. Thank you!
